package nepgap.controller;

import jakarta.servlet.http.HttpServletRequest;
import nepgap.dto.ApiResponse;
import nepgap.dto.SearchResultDTO;
import nepgap.service.SearchService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/search")
public class SearchController {

    private final SearchService searchService;
    public SearchController(SearchService searchService) { this.searchService = searchService; }

    @GetMapping
    public ResponseEntity<ApiResponse<List<SearchResultDTO>>> search(@RequestParam("q") String q, HttpServletRequest req) {
        var list = searchService.search(q);
        ApiResponse<List<SearchResultDTO>> res = ApiResponse.<List<SearchResultDTO>>builder()
                .timestamp(Instant.now())
                .status(200)
                .message("Search results")
                .data(list)
                .path(req.getRequestURI())
                .build();
        return ResponseEntity.ok(res);
    }

    @GetMapping("/tin-tuc/{normalizedQuery}")
    public Map<String, Object> getSearchResult(@PathVariable String normalizedQuery) {
        Map<String, Object> result = new HashMap<>();
        if (normalizedQuery.contains("van mieu") || normalizedQuery.contains("quoc tu giam")) {
            result.put("text", "Di tích lịch sử và kiến trúc nghệ thuật Văn Miếu - Quốc Tử Giám\n\n" +
                    "Theo tư liệu lịch sử, năm 1070, Lý Thánh Tông cho dựng Văn Miếu, đắp tượng Khổng Tử, Chu Công, tứ phối, vẽ tượng thất thập nhị hiền, bốn mùa tế tự và cho Hoàng thái tử đến học. Năm 1076, triều đình lại cho lập Quốc Tử Giám. Năm 1253 (đời Trần), đổi tên Quốc Tử Giám thành Quốc Tử viện. Đến đời Lê (năm 1483), đổi tên Quốc Tử viện thành Thái Học đường. Thời Nguyễn, khu vực này được đổi thành Văn Miếu Hà Nội.\n\n" +
                    "Trong lịch sử, di tích là nơi thờ Thánh Nho (Khổng Tử), Chu Công, tứ phối, thất thập nhị hiền, Chu Văn An và là trường Quốc Học đào tạo trí thức Nho học của nước ta từ thời Lý đến thời Lê; đồng thời cũng là nơi dựng bia “đề danh” (hiện còn 82 bia) những tiến sĩ đã đỗ đạt trong các kỳ thi tiến sĩ từ thời Lý đến thời Lê, trong đó có nhiều danh nhân trong lịch sử nước ta.\n\n" +
                    "Trải qua thời gian gần 1000 năm, các công trình kiến trúc của di tích có sự thay đổi nhất định. Hiện nay, di tích còn bảo tồn được một số hạng mục kiến trúc thời Lê và thời Nguyễn. Khu nhà Thái Học mới được Nhà nước đầu tư phục dựng năm 1999- 2000. Dựa vào công năng kiến trúc, có thể chia di tích thành hai khu vực chính: Văn Miếu - nơi thờ tự tiên Nho, và Quốc Tử Giám - trường đào tạo trí thức Nho học.\n\n" +
                    "1. Văn Miếu\n\n" +
                    "Văn Miếu được xây dựng trên khu đất hình chữ nhật (dài 300m, rộng 70m), xung quanh là tường gạch vồ, gồm các hạng mục sau:\n\n" +
                    "Hồ Văn: Ở trước mặt Văn Miếu, có diện tích 12.297m2. Trước đây, giữa hồ có gò Kim Châu, trên dựng một phương đình - “Phán Thuỷ đình”, là nơi diễn ra các buổi bình thơ của Nho sĩ. Nay phương đình đã mất, trên gò vẫn còn tấm bia dựng năm Tự Đức 18 (1865) ghi lại việc tu sửa Văn Miếu.\n\n" +
                    "Nghi môn ngoại (tứ trụ): được xây bằng gạch, hai trụ giữa xây cao hơn, đỉnh trụ đặt hai tượng nghê chầu, hai trụ ngoài thấp hơn, đỉnh trụ đắp hình chim phượng, đuôi chụm vào nhau, 4 đầu quay về 4 hướng, thân trụ đắp nổi các đôi câu đối chữ Hán. Hai bên nghi môn có 2 bia “Hạ mã” (xuống ngựa). Đây cũng là cột mốc ranh giới hiện nay của di tích.\n\n" +
                    "Nghi môn nội: được xây 2 tầng, gồm 3 cửa cuốn vòm. Trên cửa chính nghi môn nội đề 3 chữ “Văn Miếu môn”, tầng dưới to, có cầu thang lên tầng 2, tầng trên thu nhỏ, xung quanh có hành lang rộng, 4 mặt có lan can. Kiến trúc tầng 2 giống như một nghi môn 2 tầng, 8 mái, mở 3 cửa cuốn, không có cánh cửa, trên bờ nóc đắp nổi đôi rồng chầu mặt nguyệt.\n\n" +
                    "Cửa Đại Trung (Đại Trung môn): gồm 3 gian, kết cấu ba hàng chân cột, dựng trên nền gạch cao, mái lợp ngói, hai bên có 2 cửa nhỏ (“Thành Đức môn” và “Đại Tài môn”).\n\n" +
                    "Khuê Văn các: là một lầu vuông, gồm 2 tầng, 8 mái, dựng năm 1805, trên một nền vuông lát gạch Bát Tràng. Phía dưới là 4 trụ gạch, 4 phía để trống, bên trên là kiến trúc gỗ, có sàn gỗ, mái lợp ngói, 4 mặt bưng ván gỗ, mỗi phía trổ một cửa tròn, có các con tiện tượng trưng cho các tia của sao Khuê toả sáng. Phía trên treo biển đề “Khuê Văn các” (chữ Hán), cùng hệ thống câu đối. Hai bên Khuê Văn các có 2 cửa nhỏ (“Bí văn môn” và “Súc văn môn”).\n\n" +
                    "Hai dãy nhà bia tiến sĩ: gồm 82 bia tiến sĩ (được dựng từ năm 1484 đến năm 1780) của 82 khoa thi - từ khoa thi Nhâm Tuất, niên hiệu Đại Bảo 3 (1442) đến khoa thi năm 1779. Nội dung bia ghi tên, quê quán, khoa thi của 1305 vị đỗ đại khoa. Hai dãy nhà bia mới được dựng lại năm 1994, gồm 8 nhà che bia, sắp xếp bia tiến sĩ mỗi bên bốn dãy, mỗi nhà đặt 10 bia. Hai tấm bia ghi nội dung khoa thi năm 1442 và 1448 được đặt vào giữa hai toà Bi đình. Các nhà bia được dựng theo kiểu nhà có mái đao, lợp ngói mũi hài, kết cấu vì kèo “giá chiêng”, nền lát gạch bát. Bia Văn Miếu được dựng vào 3 đợt chính: niên hiệu Hồng Đức 15 (1484) dựng 10 bia; niên hiệu Thịnh Đức 1 (1653) dựng 25 bia; niên hiệu Vĩnh Thịnh 13 (1717) dựng 21 bia. Ngoài ra, các bia còn lại đều được dựng cùng niên đại với khoa thi hoặc sau khoa thi một năm. Các tấm bia đều được khắc bằng loại đá được khai thác tại núi An Hoạch, huyện Đông Sơn, tỉnh Thanh Hoá (hiện nay vẫn còn 1 tấm bia ghi lại việc lấy đá ở vùng này khắc 25 bia Văn Miếu vào năm 1653).\n\n" +
                    "Cửa Đại Thành (Đại Thành môn): hai bên cửa có 2 cửa nhỏ (Kim Thanh và Ngọc Chấn). Cửa Đại Thành gồm 3 gian, kiến trúc 3 hàng chân cột, với 2 hàng cột hiên và một hàng cột giữa đỡ xà nóc, ba gian đều được lắp cửa 2 cánh, chính giữa treo bức hoành phi đề 3 chữ “Đại Thành môn”.\n\n" +
                    "Đại bái: gồm 9 gian, 6 hàng chân cột, giữa bờ nóc đắp nổi hình lưỡng long chầu nguyệt. Gian giữa kê một hương án, là nơi xưa kia xuân, thu nhị kỳ vua cùng hoàng thân và các quan lại đến tế Khổng Tử. Đại bái xây trên nền cao hơn mặt sân 30 cm, xung quanh nền bó vỉa gạch, mái lợp ngói mũi hài, các bộ vì kết cấu kiểu “chồng rường, cốn kẻ chồng, bẩy hiên”, nền lát gạch Bát Tràng. Trang trí trên kiến trúc tập trung ở các bẩy hiên, chạm hình hoa lá cách điệu.\n\n" +
                    "Điện Đại thành: xây song song với toà Đại bái, được nối với nhau bằng một phương đình, gồm 9 gian, xây tường 3 mặt, phía trước có cửa bức bàn đóng kín 5 gian, 4 gian đầu hồi có cửa chấn song cố định. Chính giữa có khám và ngai lớn, đặt trên bệ xây gạch, trên có bài vị “Đại Thành chí thánh tiên sư Khổng tử” - nay đã bị mất, chỉ còn lại ngai và khám.\n\n" +
                    "Hai dãy nhà tả, hữu vu: mỗi dãy 9 gian, dựng trên nền cao, phong cách kiến trúc thời Hậu Lê, đầu Nguyễn, nền bó vỉa gạch, lát gạch bát, mái lợp ngói ta, bờ nóc đắp kiểu bờ đinh, kết cấu vì kèo kiểu “chồng rường”.\n\n" +
                    "2. Quốc Tử Giám\n\n" +
                    "Quốc Tử Giám xưa ở phía sau khu Văn Miếu, có giảng đường, khu nhà dành cho học sinh, kho chứa ván (gỗ) khắc in sách. Khi Quốc Tử Giám chuyển vào Huế thì khu vực này trở thành khu Khải Thánh, nơi thờ cha mẹ Khổng Tử. Hai bên tòa Khải Thánh là tả, hữu vu, giữa là một sân rộng. Hiện nay, kiến trúc khu vực này gồm các hạng mục:\n\n" +
                    "Tả, hữu vu: xây chạy dọc hai bên sân, mỗi dãy 9 gian kiểu tường hồi bít đốc, mái lợp ngói ta, bờ nóc đắp kiểu bờ đinh, kết cấu vì kèo kiểu “chồng rường”, nền lát gạch bát.\n\n" +
                    "Nhà Thái học: được dựng lại năm 1998 - 2000, gồm hai nếp nhà có kết cấu liên hoàn, mái lợp ngói mũi hài, các bộ vì đỡ mái kiểu “chồng rường, cốn chồng kẻ, bẩy hiên”, nền lát gạch bát. Cung thờ phía sau xây kiểu mái chồng diêm, lợp ngói mũi hài, kết cấu bộ vì kiểu “giá chiêng chồng rường”, nền lát gạch Bát Tràng. Tầng dưới Nhà Thái học trưng bày hiện vật, hình ảnh giới thiệu về di tích, tầng trên là nơi thờ các vị vua: Lý Thái Tông, Lý Nhân Tông, Lê Thánh Tông.\n\n" +
                    "Ngoài ra, trong khu Văn Miếu còn có một miếu thờ thổ thần và điện thờ Mẫu. Tại di tích hiện còn lưu giữ được nhiều hiện vật có giá trị văn hóa, lịch sử và khoa học, như hệ thống đồ thờ tự, tượng thờ, cổ vật, đặc biệt là 82 bia tiến sĩ đã được UNESCO vinh danh là “Di sản tư liệu thế giới”.\n\n" +
                    "Từ góc nhìn lịch sử và di sản văn hóa, có thể nhận thấy, di tích Văn Miếu- Quốc Tử Giám bao hàm các mặt giá trị tiêu biểu sau:\n\n" +
                    "* Văn Miếu - Quốc Tử Giám là Trường Quốc học đầu tiên ở nước ta, đã đào tạo được nhiều thế hệ hiền tài từ thời Lý đến thời Lê - những người đã có nhiều đóng góp lớn cho sự phát triển của đất nước. Những giá trị lịch sử, văn hóa, khoa học “kết tinh” trong di tích là “tấm gương” phản chiếu về truyền thống hiếu học, tôn sư trọng đạo, coi trọng hiền tài của dân tộc ta trong lịch sử ngàn năm văn hiến. Trong số các di tích gắn với Nho học ở nước ta, đây là một di tích Nho học tiêu biểu, có giá trị cao về mặt kiến trúc - nghệ thuật và thẩm mỹ.\n\n" +
                    "- Di tích lưu giữ nhiều hiện vật, tư liệu quý, đặc biệt là 82 bia tiến sĩ đã được UNESCO vinh danh là “Di sản tư liệu thế giới”.\n\n" +
                    "* Hiện nay, Văn Miếu - Quốc Tử Giám còn là điểm du lịch văn hóa hấp dẫn du khách, đang có những đóng góp tích cực vào sự phát triển về mọi mặt của thủ đô cũng như của cả nước.\n\n" +
                    "Với những giá trị lịch sử, văn hóa và khoa học tiêu biểu của di tích, năm 1962, Bộ Văn hóa (nay là Bộ Văn hóa, Thể thao và Du lịch) đã xếp hạng Văn Miếu- Quốc Tử Giám là Di tích quốc gia; ngày 10/5/2012, Thủ tướng Chính phủ đã quyết định xếp hạng Văn Miếu - Quốc Tử Giám là di tích quốc gia đặc biệt.");
            result.put("images", Arrays.asList(
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565051/v%C4%83n_mi%E1%BA%BFu_-_post_2_rcwqbs.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565049/bia_ti%E1%BA%BFn_s%C4%A9_-_post_2_r6uket.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565052/post_2_jlhyh4.png"
            ));
            return result;
        } else if (normalizedQuery.contains("hoa lo") || normalizedQuery.contains("nha tu hoa lo")) {
            result.put("text", "Di Tích Nhà Tù Hỏa Lò - Chứng nhân lịch sử giữa Lòng Thủ Đô\n\n" +
                    "Cuối thế kỷ XIX, nhằm đối phó với các phong trào đấu tranh của nhân dân Việt Nam, thực dân Pháp đã tăng cường bộ máy đàn áp: bổ sung lực lượng cảnh sát, hoàn chỉnh hệ thống toà án và xây dựng mạng lưới nhà tù. Năm 1896, trên đất làng Phụ Khánh - tổng Vĩnh Xương - huyện Thọ Xương - Hà Nội, thực dân Pháp đã xây dựng nhà tù Hỏa Lò. Đây là một trong số những nhà tù lớn nhất của thực dân Pháp ở Đông Dương.\n\n" +
                    "Từ một làng nghề thủ công làm đồ gốm có tiếng, thực dân Pháp đã biến mảnh đất Hỏa Lò thành nơi giam cầm và đày ải về thể xác và tinh thần của hàng ngàn chiến sỹ yêu nước, cách mạng Việt Nam. Sống trong ngục tù đế quốc, với chế độ giam cầm hà khắc, sinh hoạt đọa đày nhưng các chiến sỹ yêu nước, cách mạng vẫn giữ vững khí tiết, biến nhà tù thành trường học và là nơi phổ biến lý luận cách mạng. Nhiều người đã mưu trí vượt ngục trở về với nhân dân, với tổ chức, đóng góp xứng đáng vào sự nghiệp giải phóng dân tộc.\n\n" +
                    "Có rất nhiều nhà lãnh đạo yêu nước và cách mạng Việt Nam bị thực dân Pháp giam giữ ở nhà tù Hỏa Lò, tiêu biểu như: Phan Bội Châu, Lương Văn Can, Nguyễn Quyền, Hồ Tùng Mậu, Nguyễn Lương Bằng… và năm đồng chí Tổng Bí thư của Đảng Cộng sản Việt Nam gồm: Nguyễn Văn Cừ, Trường Chinh, Lê Duẩn, Nguyễn Văn Linh và Đỗ Mười.\n\n" +
                    "Tháng 10/1954, sau khi miền Bắc được giải phóng, Chính phủ Việt Nam đã quản lý và tạm thời sử dụng nhà tù Hoả Lò để giam giữ những người vi phạm pháp luật. Tuy nhiên, từ ngày 05/8/1964 đến 31/3/1973, nhà tù Hỏa Lò còn được dùng để giam giữ phi công Mỹ bị bắn rơi khi ném bom bắn phá miền Bắc Việt Nam. Trong thời kỳ này, phi công Mỹ đặt cho Hỏa Lò tên gọi hài hước “Hà Nội Hilton”. Những phi công Mỹ bị giam giữ tại đây có cả Douglas Peter Peterson, sau này trở thành Đại sứ Mỹ đầu tiên tại nước Cộng hoà xã hội chủ nghĩa Việt Nam và John Mc Cain - hiện là Thượng nghị sỹ Mỹ.\n\n" +
                    "Năm 1993, để đáp ứng yêu cầu phát triển kinh tế của Thủ đô, Chính phủ Việt Nam quyết định chuyển đổi mục đích sử dụng của nhà tù Hỏa Lò. Một phần phía Đông Nam còn lại được gìn giữ, tu bổ, tôn tạo để xếp hạng trở thành Di tích lịch sử của Hà Nội. Nơi đây có Đài tưởng niệm các chiến sỹ yêu nước và cách mạng Việt Nam đã anh dũng hy sinh tại nhà tù Hỏa Lò vì nền độc lập, tự do của dân tộc.");
            result.put("images", Arrays.asList(
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565057/nh%C3%A0_t%C3%B9_h%E1%BB%8Fa_l%C3%B2_-_post_3_wxlh1l.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565060/nh%C3%A0_t%C3%B9_h%E1%BB%8Fa_l%C3%B2_3_-_post_3_a81aiv.png"
            ));
            return result;
        } else if (normalizedQuery.contains("trang an")) {
            result.put("text", "Khám phá vẻ đẹp quần thể danh thắng Tràng An\n\n" +
                    "Tràng An được ví như một “Hạ Long trên cạn” với vẻ đẹp tráng lệ được tạo nên bởi hệ thống núi đá muôn hình vạn trạng soi bóng xuống những dòng suối nhỏ quanh co, uốn lượn nối liền các hang động và thung lũng hoang sơ. Vẻ hài hòa của đá, sông nước, rừng cây và bầu trời ở Tràng An tạo nên một thế giới tự nhiên sống động đầy quyến rũ. Nơi đây còn là nơi bảo tồn và chứa đựng nhiều hệ sinh thái rừng ngập nước, rừng trên núi đá vôi, các di chỉ khảo cổ học và các di tích lịch sử văn hóa đặc sắc.\n\n" +
                    "Ngoài tuyến du lịch đường bộ có chiều dài 1,6km qua ba đèo liền nhau là đèo Cậy, đèo Vài và đèo đền Trần, đến với khu du lịch sinh thái Tràng An, du khách còn có thể lựa chọn tuyến du lịch đường thủy kết hợp leo núi theo một lộ trình khép kín. Xuất phát từ bến thuyền trung tâm với điểm dừng chân đầu tiên là đền Trình, tiếp theo du khách ngồi thuyền qua các hang Địa Linh, hang Tối, hang Sáng, hang Nấu Rượu rồi lên bờ và leo gần 500 bậc đá để vào dâng hương tại đền Trần. Sau đó, du khách xuống thuyền đi qua hang Sính, hang Si, hang Ba Giọt, hang Seo, hang Sơn Dương và lên thăm phủ Khống, rồi tiếp tục lộ trình đến hang Khống, hang Trần, hang Quy Hậu và trở về điểm xuất phát, kết thúc chuyến đi.\n\n" +
                    "Cùng với khu du lịch sinh thái Tràng An, khu du lịch Tam Cốc-Bích Động là một trong những khu hấp dẫn của tỉnh Ninh Bình. Tam Cốc nghĩa là 3 hang, gồm hang Cả, hang Hai và hang Ba. Đến với Tam Cốc, du khách sẽ được ngồi thuyền tham quan, ngắm cảnh trời, mây, sông nước, núi non hùng vĩ. Mỗi mùa một vẻ, Tam Cốc luôn quyến rũ du khách đến chiêm ngưỡng vẻ đẹp mà tạo hóa đã ban tặng cho nơi đây. Bích Động, nghĩa là động xanh, được mệnh danh là “Nam thiên đệ nhị động. Bích Động cùng chùa Bích Động là tác phẩm nghệ thuật cổ kính, trang nghiêm của con người hòa nhập trong khung cảnh thiên nhiên tươi xanh, tĩnh lặng, góp thêm cho bức tranh toàn cảnh của Quần thể danh thắng Tràng An được hoàn mỹ.\n\n" +
                    "Quần thể danh thắng Tràng An còn bao bọc khu rừng nguyên sinh đặc dụng Hoa Lư với hệ sinh thái đa dạng, phong phú, trong đó có những loài động vật quý hiếm như phượng hoàng đất, sáo, khướu, khỉ, trăn, đặc biệt là loài vượn yếm trắng, một loài có tên trong sách đỏ thế giới.\n\n" +
                    "Bên cạnh những giá trị nổi bật về cảnh quan và địa chất, quần thể danh thắng Tràng An còn có những di chỉ khảo cổ học như hang Búi, hang Trống, núi hang Chợ…, minh chứng cho quá trình sinh tồn của người cổ đại tại mảnh đất này từ hàng vạn năm trước. Là hệ thống phòng thủ phía Nam của kinh đô Hoa Lư xưa, nơi đây còn có sự hiện hữu của những di tích gắn liền với ba triều đại Đinh - Tiền Lê - Lý, kết nối với quần thể di tích lịch sử cố đô Hoa Lư, trong đó nổi bật là đền thờ và lăng mộ vua Đinh Tiên Hoàng, đền thờ và lăng mộ vua Lê Đại Hành, nhà bia tưởng niệm vua Lý Thái Tổ, trung tâm văn hóa tâm linh chùa Bái Đính - quần thể chùa lớn nhất Đông Nam Á và hội tụ nhiều kỷ lục ở Việt Nam và châu Á... Chính vì vậy, tìm hiểu và khám phá những di tích và giá trị văn hóa cũng chính là một trong những trải nghiệm không thể bở lỡ trong chuyến hành trình khám phá danh thắng Tràng An.\n\n" +
                    "Đến với Tràng An, du khách còn có thể tham gia vào nhiều hoạt động trải nghiệm đặc sắc như trèo thuyền kayak, tham quan, ngắm cảnh Quần thể danh thắng Tràng An bằng máy bay trực thăng, hay thưởng thức những món ăn đặc sản của địa phương như thịt dê, cơm cháy... Bên cạnh đó, sự nhiệt tình, chu đáo, thân thiện của đội ngũ hướng dẫn viên và người dân địa phương cũng là yếu tố góp phần thu hút du khách đến và quay trở lại nơi đây.\n\n" +
                    "Với những giá trị đặc sắc về văn hóa, vẻ đẹp thẩm mỹ và địa chất - địa mạo, Quần thể danh thắng Tràng An đã được Ủy ban Di sản Thế giới thuộc Tổ chức Giáo dục, Khoa học và Văn hóa của Liên hợp quốc (UNESCO) công nhận là Di sản Văn hóa và Thiên nhiên thế giới vào năm 2014.");
            result.put("images", Arrays.asList(
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565062/tr%C3%A0ng_an_-_post_4_eldyiz.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565065/post_4_-_tr%C3%A0ng_an_briuuq.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565066/tr%C3%A0ng_an_2_-_post_4_jf9nf9.png"
            ));
            return result;
        } else if (normalizedQuery.contains("hoa lu") || normalizedQuery.contains("co do hoa lu")) {
            result.put("text", "Khám Phá Vẻ Đẹp Cố Đô Hoa Lư - Dấu Ấn Lịch Sử Hào Hùng Dân Tộc Việt\n\n" +
                    "Cố đô Hoa Lư là điểm đến đậm đà giá trị văn hóa và lịch sử dân tộc. Mặc thời gian thoi đưa, cố đô vẫn yên bình nằm đó, tuy trầm mặc nhưng vẫn đầy uy nghi, là dấu ấn vàng son đánh dấu một thời dân tộc oai hùng. Vậy thật ra nơi cố đô có gì mà ai cũng khao khát được một lần ghé đến, hãy cùng tìm hiểu với Nếp Gấp Non Sông nhé!\n\n" +
                    "Cố Đô Hoa Lư ngự tại xã Trường Yên, huyện Hoa Lư, tỉnh Ninh Bình.\n\n" +
                    "Sở hữu diện tích rộng rãi ấn tượng lên đến 300ha với các công trình kiến trúc có giá trị cao về mặt văn hóa, lịch sử cùng cảnh sắc non nước hữu tình, Cố đô Hoa Lư là một trong bốn vùng lõi thuộc Quần thể danh thắng Tràng An, được UNESCO chính thức công nhận là Di sản văn hóa kép đầu tiên và duy nhất tại Đông Nam Á vào năm 2014. Cố đô cũng là một trong những điểm tham quan tại Ninh Bình được nhiều người yêu thích bậc nhất hiện nay.\n\n" +
                    "Ngược dòng thời gian tìm hiểu về bề dày lịch sử trong 42 năm nơi Cố đô Hoa Lư\n\n" +
                    "Cố đô Hoa Lư là đế đô đầu tiên của nước ta, tồn tại trong 42 năm. Mảnh đất này là nơi đã chứng kiến sự nghiệp dựng nước và giữ nước oai hùng của 12 năm triều Đinh (968 – 980), 29 năm triều Tiền Lê (980 – 1009) và đầu nhà Lý (1009 – 1010).\n\n" +
                    "Với địa thế đồi núi trùng điệp bao bọc xung quanh vành đai kinh đô như tấm bình phong vững chãi, cùng dòng Hoàng Long uốn khúc và cánh đồng Nho Quan, Gia Viễn với hào sâu, Hoa Lư là vùng đất có giá trị cao về mặt quân sự. Chính tại vùng đất này, năm 968, Đinh Bộ Lĩnh đã dẹp loạn 12 sứ quân, lên ngôi hoàng đế, lập ra nước Đại Cồ Việt oai hùng, và Hoa Lư trở thành trung tâm chính trị, đồng thời là đế đô đầu tiên của nước ta.\n" +
                    "Đến thời vua Lý Thái Tổ, ông đã đưa ra quyết định dời đô lịch sử, và Hoàng thành Thăng Long chính là nơi được lựa chọn khi nhận ra kinh đô Hoa Lư chật hẹp, khó mở mang thành đô và không phù hợp với vị thế đất nước lúc bấy giờ. \n\n" +
                    "Chính quyết định mang tính chất lịch sử này đã kết thúc những tháng ngày Hoa Lư là vùng đất cố đô của nước ta. Tuy nhiên, hệ thống triều đình và cơ sở vật chất của Hoàng thành Thăng Long lúc bấy giờ đều thừa hưởng từ kinh đô Hoa Lư ngày trước. Tuy sau này các vua không sinh sống tại đây nữa, nhưng Cố đô Hoa Lư vẫn tiếp tục được xây dựng những công trình kiến trúc kiên cố với đền, chùa, đền thờ và được bảo tồn cho đến tận ngày nay.\n" +
                    "Cố đô Hoa Lư – Dấu ấn về một thời vàng son của dân tộc\n\n" +
                    "Nếu có dịp về với vùng đất cố đô trong hành trình khám phá Ninh Bình, bạn chắc chắn sẽ ngạc nhiên trước cảnh sắc trầm mặc, hoài cổ và phảng phất dư vị thời gian nơi đây. Nhưng ở đâu đó nơi thành lũy bờ tường, bạn vẫn sẽ nhận ra nét uy nghi, oai linh của một đế đô nguy nga tráng lệ ngày trước. Với diện tích rộng rãi ấn tượng lên đến hơn 300ha, Cố đô Hoa Lư là quần thể di tích với các công trình kiến trúc tường thành, hang động, đền chùa, lăng mộ và những công trình khác có giá trị lịch sử và văn hóa cao. Cố đô được chia làm 3 vùng, bao gồm: vùng bảo vệ đặc biệt, vùng đệm và các di tích liên quan.\n\n" +
                    "Vùng bảo vệ đặc biệt bao gồm toàn bộ khu vực bên trong thành Hoa Lư, với những di tích còn tồn tại cho đến ngày nay như đền vua Lê Đại Hành, đền vua Đinh Tiên Hoàng, đền thờ Công chúa Phất Kim, chùa Nhất Trụ, phủ Vườn Thiên, chùa Kim Ngân, bia Câu Dền, chùa Cổ Am, phủ Chợ, hang Bim, chùa Duyên Ninh, sông Sào Khê và tường thành, nền điện dưới lòng đất.\n\n" +
                    "Trong khi đó, vùng đệm của Cố đô Hoa Lư lại bao gồm khu vực cảnh quan hai bên dòng Sào Khê, Quần thể danh thắng Tràng An với hệ thống chùa và Động Am Tiên, đình Yên Trạch, hang Muối, hang Quàn, hang Sinh Dược, hang Luồn, hang Địa linh, hang Ba Giọt, hang Nấu Rượu, chùa Bà Ngô, đền Trần, phủ Khống, phủ Động, động Liên Hoa, hang Bói, v.v.");
            result.put("images", Arrays.asList(
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565068/c%E1%BB%91_%C4%91%C3%B4_hoa_l%C6%B0_-_post_5_fh6qtn.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565075/c%E1%BB%91_%C4%91%C3%B4_hoa_l%C6%B0_3-_post_5_oiizqd.png",
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565079/c%E1%BB%91_%C4%91%C3%B4_hoa_l%C6%B0_2-_post_5_d5sca4.png"
            ));
            return result;
        } else if (normalizedQuery.contains("my son") || normalizedQuery.contains("thanh dia my son")) {
            result.put("text", "Thánh Địa Mỹ Sơn - Di Sản Văn Hóa Thế Giới\n\n" +
                    "Vị độ Bắc: 15°505\nKinh độ Đông: 108°573\nTổng diện tích: 1.158ha\nThôn Mỹ Sơn - Xã Thu Bồn - Thành phố Đà Nẵng\n\n" +
                    "Thánh địa Mỹ Sơn tọa lạc trong một thung lũng kín có địa thế núi non hùng vĩ, thâm nghiêm. Nơi đây, với hơn 70 công trình kiến trúc đền tháp của nền văn minh Chămpa được kết tinh trong những di chứng vật chất trường tồn, chứa đựng những giá trị về lịch sử, văn hóa, kiến trúc, nghệ thuật được tạo lập trong một thời gian dài suốt 9 thế kỷ (từ thế kỷ thứ IV đến thế kỷ XIII), được đánh giá ngang hàng với các di tích nổi tiếng trong khu vực Đông Nam á như Ăngko, Pagan, Bôrôbudua.\n\n" +
                    "Kazik (Kazimierz - Kwiatkowski) - người kiến trúc sư tài ba nhiều năm gắn bó với Mỹ Sơn đã thốt lên \"người Chămpa cổ đã gửi tâm linh vào đất đá; và đã biết dựa vào thiên nhiên để làm nên một Mỹ Sơn tráng lệ - thâm nghiêm - hùng vĩ. Đây là một bảo tàng kiến trúc điêu khắc nghệ thuật vô giá của nhân loại mà sẽ còn lâu chúng ta mới hiểu hết\"\n\n" +
                    "Thời gian và chiến tranh đã tàn phá di tích nặng nề. Nhưng những gì còn lại ở Mỹ Sơn vẫn đóng một vài trò cực kỳ quan trọng trong di sản lịch sử văn hóa kiến trúc nghệ thuật thế giới.\n\n" +
                    "Trước những giá trị nổi bật toàn cầu của một khu di sản văn hóa cần phải được bảo vệ vì lợi ích của cả nhân loại, ngày 4 tháng 12 năm 1999, tại thành phố Marr kesk -Nước cộng hòa Marocco, khu di tích Mỹ Sơn được ghi danh vào danh sách di sản văn hóa thế giới của UNESCO.\n\n" +
                    "Không gian Thánh địa\n\n" +
                    "Không gian Mỹ Sơn là sự thâm nghiêm của núi rừng, phảng phất nét tâm linh. Núi Mhadravata với độ cao 730m ( so với mực nước biển), tên gọi được chép trong văn bia đầu tiên tại Mỹ Sơn vào thế kỷ thứ IV. Nhiều giả thuyết cho rằng ngọn núi này là một đại Linga của thần Siva dựng trong lòng thung lũng - đại Yoni, tạo nên một bộ Linga -Yoni tự nhiên khổng lồ. Mahapavata được ví như ngọn núi Meru trong thần thoại Ấn Độ, nơi trú ngụ của thần linh. Xưa kia các thương thuyền nước ngoài đi lại trên biển Đông xem ngọn núi này như ngọn hải đăng và là cột mốt xác định vị trí thánh địa Mỹ Sơn cũng như vương quốc Chămpa. Từ đỉnh núi nhìn về Mỹ Sơn, những công trình đền tháp như ngọn đuốc sáng giữa màu xanh núi rừng.\n\n" +
                    "Suối thiêng/sông thiêng chảy giữa lòng thung lũng tạo nên phức hệ núi đồi, sông suối mang đến trung tâm tôn giáo này những đa dạng của hệ sinh thái, vừa mang lại dòng nước quang năm trong lành cho lễ tẩy trần vào mùa Hindu. Một yếu tố địa văn háo độc đáo.\n\n" +
                    "Không gian bảo tồn Mỹ Sơn còn lưu giữ trong lòng nó nhiều động thực vật có giá trị khoa học và nghiên cứu. Thực vật có sến, trắc, lim, dẽ đỏ, tràm thị... động vật có gà gô, tắc kè bay, heo rừng, mang lớn...\n\n" +
                    "Kiến trúc nghệ thuật\n\n" +
                    "Với quá trình xây dựng liên tục suốt từ thế kỷ IV cho đến giữa thế kỷ XIII, các đền tháp ở Mỹ Sơn là những công trình kiến trúc chính thống của quốc gia và đều do các đời vua trị vì xây dựng, vì vậy có thể nói rằng đền tháp là nơi tập trung thể hiện những gì tiêu biểu nhất, tinh hoa nhất điển hình cho nền kiến trúc nghệ thuật đương thời với những dạng thể kiến trúc độc đáo. Hầu hết các phong cách kiến trúc đền tháp Chăm đều có mặt ở Mỹ Sơn và chính bản thân các đền tháp ở Mỹ Sơn lại tạo nên những tiêu chí cơ bản cho việc nhận diện phong cách kiến trúc nghệ thuật Chăm.\n\n" +
                    "Trong số các dạng kiến trúc tháp Chăm, kiến trúc dạng quần thể thánh địa như Mỹ Sơn là độc đáo và hiếm có. Được bố trí theo cụm, từ hai hoặc nhiều tháp. Có tường bao, sân, đường đi nối các tháp với nhau. Mỗi tháp có mỗi chức năng riêng. Tập trung thành từng nhóm, trong đó đền thờ chính nằm ở giữa, mỗi nhóm đều được bao quanh bởi những bức tường khá dày cũng bằng gạch. Cửa chính của tháp chính phần lớn quay về hướng Đông (hướng về thần linh). Một vài tháp lớn chính có thêm cửa hướng Tây. Trước mặt đền thờ chính (KaLan) là một tháp cổng (Gopura) với cấu trúc nhỏ của hai cửa thông nhau: một cửa về hướng Đông, một cửa hướng vào đền chính, tiếp với tháp cổng thường là căn nhà dài (Mandapa) có mái lợp ngói, bên trong rộng rãi vốn là nơi đón khách hành hương và tiếp nhận lễ vật cũng như cử hành các vũ điệu trong các lễ cúng hiến cho thần linh. Xung quanh ngôi đền chính là các ngôi đền nhỏ hoặc các công trình phụ.\n\n" +
                    "Phong phú nhất trong kho tàng văn hóa Chăm Mỹ Sơn là hệ thống tượng thần, tu sĩ, hoa văn trang trí, cỏ cây, muôn thú. Thiên nhiên vũ trụ là sự giao hòa, đồng nhất. Tất cả được sáng tạo tỉ mỉ, cần mẫn cùng với cấu trúc đền thờ, không gian hành lễ ghi dấu những nghi thức tôn giáo, thờ cúng, thấm đượm niềm sung kính thiêng liêngnhưng vẫn mang tính khoáng đạt vốn rất đặt trưng của tâm hồn Chămpa.\n\n" +
                    "Rực rỡ và thành công với mảng vật liệu nề, với kỹ thuật cao và hiện đại. Đền thờ đứng vững theo thời gian hàng ngàn năm. Biểu tượng cho một giai đoạn phát triển về mảng kiến trúc trong lịch sử xây dựng. Việc xử lí chất liệu thể hiện yếu tố kỹ mỹ thuật, những tính toán độ bền, kỹ thuật nung, tỉ lệ xây dựng, nền móng cho thấy bàn tay và khối óc tài hoa của người xưa.\n\n" +
                    "Không đồ sộ kỳ vĩ như Ăngko (Campuchia), Pagan (Myanma), Bôrôbudua Kala( Inđônêsia) nhưng Mỹ Sơn vẫn có một chỗ đứng quan trọng trong nên nghệ thuật Đông Nam á bởi nó là khu di tích duy nhất của cả khu vực có thời gian phát triển liên tục gần 9 thế kỷ.\n\n" +
                    "Với lịch sử phát triển lâu dài, Mỹ Sơn trở thành mảnh đất để những kiệt tác nghệ thuật, những tinh hoa văn hóa bừng cháy. Nơi hội tụ của nhiều phong cách kiến trúc Chăm. Từ phong cách cổ (Mỹ Sơn E1), Hòa Lai, Đồng Dương, Mỹ Sơn A1, Ponaga, Bình Định. Tất cả thể hiện trên đất nung và đá sa thạch, vật liệu là thế mạnh của nghệ thuật Chămpa.\n\n" +
                    "Một kho tàng văn hóa rực rỡ, một bảo tàng sinh động, mang giá trị thẩm mỹ của nhân loại. Nghệ thuật Mỹ Sơn đã thể hiện đây là mảnh đất của sự khẳng định giao thoa của nhiều nền văn hóa. Trong đó đầu tiên là Ấn Độ thuần túy, sau đó là bản địa, cuối cùng là hội nhập.\n\n" +
                    "Mỹ Sơn là một công trình nghệ thuật đặc sắc, độc đáo có giá trị đến ngày hôm nay. Một kỳ quan của tinh hoa nhân loại.");
            result.put("images", Arrays.asList(
                    "https://upload.wikimedia.org/wikipedia/commons/7/7c/Th%C3%A1nh_%C4%91%E1%BB%8Ba_M%E1%BB%B9_S%C6%A1n_1.JPG",
                    "https://upload.wikimedia.org/wikipedia/commons/8/8a/0040223_My_Son_Group_H%2C_Cham_Hindu_temples_complex%2C_Vietnam_029.jpg"
            ));
            return result;
        } else if (normalizedQuery.contains("quang tri") || normalizedQuery.contains("thanh co quang tri")) {
            result.put("text", "Những dấu tích còn lại của thành cổ Quảng Trị - Một chiến trường khốc liệt\n\n" +
                    "Nằm lặng lẽ bên dòng sông Thạch Hãn hiền hòa, thành cổ Quảng Trị là chứng nhân lịch sử ghi dấu những tháng ngày khốc liệt nhất của cuộc kháng chiến chống Mỹ cứu nước. Không chỉ là một công trình kiến trúc quân sự vững chãi từ thời nhà Nguyễn, nơi đây còn khắc sâu vào tâm khảm người dân Việt Nam những ký ức đau thương nhưng hào hùng về 81 ngày đêm rực lửa năm 1972. Trải qua bao thăng trầm lịch sử, thành cổ Quảng Trị vẫn đứng đó, với những vết tích đạn bom in hằn trên từng bức tường gạch rêu phong, nhắc nhở thế hệ hôm nay về sự hy sinh to lớn của cha ông vì độc lập, tự do của Tổ quốc. \n\n" +
                    "1. Lịch sử thành cổ Quảng Trị - Nơi ghi dấu vết thời gian\n\n" +
                    "Là một trong những di tích lịch sử quan trọng, Thành cổ Quảng Trị không chỉ là chứng nhân của những sự kiện lịch sử đầy bi tráng, mà còn là nơi lưu giữ những giá trị văn hóa, khắc sâu trong lòng mỗi du khách. Hãy cùng khám phá hành trình vượt thời gian tại nơi này!\n\n" +
                    "* Lịch sử và ý nghĩa\n\n" +
                    "Thành cổ Quảng Trị được xây dựng từ thời vua Gia Long vào năm 1809 và hoàn thiện dưới triều vua Minh Mạng vào năm 1837. Ban đầu, thành được đắp bằng đất, sau đó được xây lại bằng gạch với kiến trúc hình vuông độc đáo, chu vi hơn 2.000m, tường thành cao hơn 4m và dày 12m ở chân. Với bốn pháo đài ở bốn góc và hệ thống hào bao quanh, thành không chỉ là trung tâm hành chính, kinh tế, quân sự của tỉnh Quảng Trị mà còn là pháo đài bảo vệ kinh đô Huế dưới thời nhà Nguyễn.\n" +
                    "Trong thời Pháp thuộc, từ năm 1929, thực dân Pháp biến nơi đây thành nhà lao giam giữ các chiến sĩ yêu nước. Đến năm 1972, Thành cổ Quảng Trị trở thành tâm điểm của cuộc chiến 81 ngày đêm, được mệnh danh là \"mùa hè đỏ lửa\" - một trong những trận đánh khốc liệt nhất trong lịch sử chiến tranh Việt Nam.\n\n" +
                    "* Cuộc chiến 81 ngày đêm\n\n" +
                    "Năm 1972, trong bối cảnh hội nghị đàm phán Paris đang diễn ra, Thành cổ Quảng Trị trở thành điểm nóng chiến lược. Quân Giải phóng miền Nam Việt Nam quyết giữ từng tấc đất, trong khi Mỹ và quân đội Việt Nam Cộng hòa dồn toàn lực để tái chiếm. Trong 81 ngày đêm (từ 28/6 đến 16/9/1972), thị xã Quảng Trị hứng chịu 328.000 tấn bom đạn, tương đương sức công phá của 7 quả bom nguyên tử ném xuống Hiroshima. Mỗi mét vuông đất ở đây thấm đẫm máu của các chiến sĩ, biến nơi này thành \"nghĩa trang không nấm mồ\".\n\n" +
                    "Những câu chuyện về tinh thần quả cảm của các chiến sĩ vẫn còn vang vọng. Cựu binh Đào Chí Thành từng kể rằng, giữa lằn ranh sinh tử, các chiến sĩ vẫn chiến đấu với tinh thần lạc quan, như thể họ đang tham gia một bộ phim hào hùng.\n\n" +
                    "2. Những dấu tích còn lại của thành cổ Quảng Trị\n" +
                    "Sau cuộc chiến khốc liệt năm 1972, Thành cổ Quảng Trị gần như bị san phẳng. Chỉ còn sót lại cửa Đông tương đối nguyên vẹn, cùng một vài đoạn tường thành chi chít vết bom đạn và hệ thống giao thông hào. Những dấu tích này là minh chứng sống động cho sự tàn khốc của chiến tranh, nơi hàng ngàn chiến sĩ đã hy sinh, hòa mình vào lòng đất mẹ.\n\n" +
                    "Từ thập niên 90 của thế kỷ 20, tỉnh Quảng Trị đã tiến hành tôn tạo di tích, phục chế bốn cổng chính và một số đoạn tường thành. Ở trung tâm thành, một đài tưởng niệm được xây dựng, mang hình dáng một nấm mồ chung, nơi an nghỉ của những linh hồn liệt sĩ. Đài tưởng niệm cao 8,1m, tượng trưng cho 81 ngày đêm khói lửa, với thiết kế theo triết lý âm dương, gửi gắm mong ước siêu thoát cho các anh hùng.\n\n" +
                    "Bên cạnh đài tưởng niệm, Thành cổ Quảng Trị còn có tháp chuông khánh thành năm 2007, nơi tiếng chuông ngân vang trong các dịp lễ lớn, như Ngày Thương binh - Liệt sĩ (27/7). Dọc bờ sông Thạch Hãn, bến hoa đăng là nơi diễn ra nghi thức thả đèn hoa đăng, một hoạt động tâm linh đầy xúc động để tri ân các liệt sĩ. Bảo tàng Thành cổ Quảng Trị là nơi lưu giữ những di vật quý giá, từ những bức thư vĩnh biệt của các chiến sĩ đến những hiện vật chiến tranh. Mỗi kỷ vật là một câu chuyện, một ký ức sống động về những ngày tháng hào hùng.");
            result.put("images", Arrays.asList(
                    "https://upload.wikimedia.org/wikipedia/commons/0/0f/Th%C3%A0nh_c%E1%BB%95_Qu%E1%BA%A3ng_Tr%E1%BB%8B_%28h%E1%BB%8Da_ti%E1%BA%BFt_c%E1%BB%95ng_th%C3%A0nh%29%2C_T%E1%BA%BFt_n%C4%83m_2018_%2861%29.jpg",
                    "https://upload.wikimedia.org/wikipedia/commons/4/4e/Th%C3%A0nh_c%E1%BB%95_Qu%E1%BA%A3ng_Tr%E1%BB%8B_%28C%C3%A2y_%C4%91%C3%A8n_Thi%C3%AAn_M%E1%BB%87nh%29%2C_T%E1%BA%BFt_n%C4%83m_2018_%2819%29.jpg"
            ));
            return result;
        } else if (normalizedQuery.contains("dinh doc lap")) {
            result.put("text", "Dinh Độc Lập - Dấu ấn đặc biệt về chiến thắng lịch sử của dân tộc\n\n" +
                    "Dinh Độc Lập được công nhận là Di tích lịch sử văn hóa quốc gia bằng Quyết định số 77A/VHQĐ ngày 25/6/1976 của Bộ trưởng Bộ Văn hóa. Ngày 12 tháng 8 năm 2009, Thủ tướng Chính phủ nước Cộng hòa Xã hội Chủ nghĩa Việt Nam đã ký Quyết định số 1272/QĐ-TTg xếp hạng Di tích lịch sử Dinh Độc Lập là một trong 10 di tích quốc gia đặc biệt đầu tiên của cả nước.\n\n" +
                    "Cơ quan quản lý Di tích lịch sử Dinh Độc Lập là Hội trường Thống Nhất. Căn cứ Quyết định số 709/QĐ-VPCP ngày 14 tháng 6 năm 2013 của Bộ trưởng, Chủ nhiệm Văn phòng Chính phủ qui định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Hội trường Thống Nhất, thì Hội trường Thống Nhất là đơn vị sự nghiệp công lập thuộc Văn phòng Chính phủ có chức năng quản lý, bảo tồn, tôn tạo Di tích lịch sử Dinh Độc Lập; phục vụ đại biểu, khách tham dự các cuộc họp, hội nghị của Chính phủ, Thủ tướng Chính phủ và Văn phòng Chính phủ; các hội nghị và hoạt động khác của Đảng, Nhà nước, Quốc hội khi có yêu cầu; được tận dụng cơ sở vật chất, lao động để kinh doanh dịch vụ theo qui định của pháp luật.\n\n" +
                    "Hội trường Thống Nhất hiện có các phòng chức năng sau:\n\n" +
                    "* Phòng Nghiệp vụ Thuyết minh\n\n" +
                    "* Phòng Kế hoạch Tài vụ\n\n" +
                    "* Phòng Bảo vệ\n\n" +
                    "* Phòng Hành chính Tổ chức\n\n" +
                    "* Phòng Quản trị\n\n" +
                    "* Nhà khách 108 Nguyễn Du, P. Bến Thành, Tp Hồ Chí Minh.\n\n" +
                    "* Nhà khách 17 Thùy Vân, Bãi sau, Tp Hồ Chí Minh.\n\n" +
                    "Trước ngày 30/4/1975 lịch sử, Dinh Độc Lập là một trong những cơ quan đầu não của chính quyền Sài Gòn, nơi chứng kiến sự can thiệp quân sự của nước ngoài gây chiến tranh tàn khốc ở Việt Nam. Sau ngày giải phóng, đây là công trình kiến trúc đặc sắc, di tích lịch sử đặc biệt - nơi lưu giữ dấu ấn về ngày chiến thắng, kết thúc Chiến dịch Hồ Chí Minh lịch sử, giải phóng miền Nam, thống nhất đất nước. Đây cũng là ý nghĩa của tên gọi hiện tại của công trình - Hội trường Thống nhất.\n\n" +
                    "Dấu ấn ngày 30/4 lịch sử\n\n" +
                    "Những ngày cuối tháng 4/1975, Chiến dịch Hồ Chí Minh với năm cánh quân theo năm hướng tiến hành tổng công kích Sài Gòn - Gia Định. Các cánh quân hừng hực khí thế, cùng chiến lược tấn công “thần tốc’ đã làm nội bộ chính quyền ngụy Sài Gòn phân hóa mạnh mẽ.\n" +
                    "Đại tá Nguyễn Văn Tàu (Bí danh Trần Văn Quang - Tư Cang), Anh hùng Lực lượng vũ trang Nhân dân, lúc bấy giờ là Chính ủy Lữ đoàn 316 Đặc công Biệt động, đơn vị cùng với Quân đoàn 3 (Binh đoàn Tây Nguyên) theo hướng Tây Bắc chia các mũi tấn công hướng về Dinh Độc Lập, nay đã 98 tuổi nhưng ông vẫn nhớ tất cả những sự kiện lịch sử quan trọng, đặc biệt là ngày 30/4/1975.\n\n" +
                    "Ông Tư Cang nhớ lại, khi các đoàn quân tiến về Sài Gòn như “thác đổ”, đến 9 giờ 30 phút sáng 30/4/1975, tại Dinh Độc lập, Tổng thống Dương Văn Minh phát đi tuyên bố trên đài phát thanh Sài Gòn quyết định đơn phương ngừng bắn và trao quyền lại cho Chính phủ Cách mạng lâm thời Cộng hòa miền Nam Việt Nam. Tuy nhiên lời tuyên bố lúc đó đã không còn giá trị. Cùng lúc đó, mũi thọc sâu của Quân đoàn 2, sau khi đè bẹp một số mục tiêu quan trọng ở Thủ Đức, lần lượt vượt qua cầu Sài Gòn và cầu Thị Nghè tiến thẳng về hướng Dinh Độc Lập.\n\n" +
                    "Đúng 11 giờ 30 phút ngày 30/4/1975 - thời khắc báo hiệu Chiến dịch Hồ Chí Minh lịch sử đã toàn thắng. Dinh Độc Lập trở thành “chứng nhân” lịch sử, là nơi lưu giữ dấu ấn của chiến thắng vàng son, ghi dấu thời khắc kết thúc của chính quyền Sài Gòn.\n" +
                    "Hồi tưởng lại khoảnh khắc lịch sử, Đại úy Vũ Đăng Toàn, nguyên là Đại đội trưởng, Trưởng xe tăng đã húc đổ cổng Dinh Độc Lập vào trưa 30/4, từng chia sẻ: \"Đó là khoảnh khắc tuyệt vời nhất, oai hùng nhất không thể nào quên của ông và các đồng đội. Để xe tăng của ta tiếp cận được cổng Dinh Độc Lập là biết bao nhiêu chiến sĩ, đồng bào ta đã hy sinh. Chính tôi cũng không ngờ rằng mình được chứng kiến những giây phút lịch sử chói lọi đó của Chiến dịch Hồ Chí Minh vĩ đại\".\n\n" +
                    "Công trình biểu tượng về Thống nhất\n\n" +
                    "Được xây dựng vào năm 1868, Dinh Độc Lập có tên ban đầu là Dinh Norodom. Đến năm 1962, Dinh được xây dựng lại theo đồ án thiết kế của kiến trúc sư Ngô Viết Thụ, người Việt Nam đầu tiên đoạt giải thưởng Khôi nguyên La Mã (Giải thưởng danh giá dành cho những tài năng trẻ trong lĩnh vực âm nhạc, hội họa, điêu khắc và kiến trúc). Qua lời kể của kiến trúc sư Ngô Viết Nam Sơn, con trai của ông Ngô Viết Thụ, cha ông đã khéo léo gửi gắm thông điệp về chủ quyền của Việt Nam trong thiết kế tổng thể mặt tiền Dinh Độc Lập.\n\n" +
                    "“Ý nghĩa triết tự đưa vào mặt tiền của Dinh Độc Lập, gồm có: Chữ “tam” ba nét ngang (viết nhân, viết minh, viết võ); thêm nét dọc là chữ “chủ” mang ý nghĩa nhấn mạnh chủ quyền của Việt Nam; trên cùng là chữ “trung” nhắc đến ý nghĩa là phải “trung với nước” và hình ảnh mặt tiền chung tạo thành chữ “hưng” thể hiện mong cầu của nhà thiết kế về đất nước hưng thịnh mãi”, kiến trúc sư Ngô Viết Nam Sơn cho biết.\n\n" +
                    "Vẻ đẹp kiến trúc của Dinh Độc Lập còn được thể hiện qua bức rèm hoa đá mang hình dáng những đốt trúc thanh tao bao xung quanh tầng 2. Ở thời điểm đó, kiến trúc sư Ngô Viết Thụ đã kiến tạo một công trình mang phong cách kiến trúc hiện đại dựa trên tư duy triết lý phương Đông rõ nét. Bức rèm đó cũng lấy ý tưởng từ lối kiến trúc cổ ở các bức cửa bàn khoa trong cung đình Huế. Một điểm khác biệt khác là thay vì làm mái cong lặp lại kiến trúc cổ điển của Việt Nam thì ông Ngô Viết Thụ đã đưa ra phương án làm một mái bê tông khoét nhẹ tạo dáng một hình cong để gợi lại hình ảnh của kiến trúc xưa, nhưng với một tinh thần hoàn toàn hiện đại.\n\n" +
                    "Tiến sĩ Tạ Duy Linh, Viện trưởng Viện Nghiên cứu Kinh tế - Du lịch TP Hồ Chí Minh cho rằng: Dinh Độc Lập không chỉ là một di tích quốc gia đặc biệt mà còn là một không gian biểu tượng độc đáo của văn hóa chính trị Việt Nam hiện đại. Từ trung tâm quyền lực mang tính lịch sử, nơi đây đã chuyển hóa thành điểm hội tụ của ký ức dân tộc, khát vọng hòa bình, thống nhất lãnh thổ và hòa hợp cộng đồng trong một quốc gia từng trải qua chia cắt. Từ góc nhìn văn hóa học, Dinh Độc lập không chỉ tượng trưng cho sự kết thúc của chiến tranh mà còn mở ra một diễn ngôn lớn về sự thống nhất và hòa hợp dân tộc.\n\n" +
                    "Theo Tiến sĩ Tạ Duy Linh, trong tầng sâu biểu tượng, Dinh Độc Lập chính là nơi kết tinh của ý chí hòa hợp, thống nhất, nơi quá khứ được tưởng niệm không phải để khơi lại. Đây là không gian của bản lĩnh Việt Nam, biết vượt lên nỗi đau, hóa giải khác biệt bằng tinh thần bao dung và biến ký ức lịch sử thành động lực để kiến tạo một quốc gia thống nhất về ý chí, đoàn kết trong hành động. Vì vậy, việc bảo tồn và phát huy giá trị của Dinh ngày nay cần đặt trong một chiến lược văn hóa hiện đại, nhằm làm sống lại biểu tượng chứ không chỉ “đóng khung” trong hoài niệm. “Dinh Độc Lập có thể trở thành một trung tâm giáo dục công dân, một không gian trải nghiệm di sản, nơi thế hệ trẻ được truyền cảm hứng để hiểu rằng hòa bình, thống nhất và hòa hợp không phải là điều đã xong, mà là hành trình cần tiếp tục nuôi dưỡng qua từng thế hệ”, Tiến sĩ Tạ Duy Linh nói.");
            result.put("images", Arrays.asList(
                    "https://upload.wikimedia.org/wikipedia/commons/7/7b/Independence_Palace_or_Reunification_Palace_%2812110973526%29.jpg",
                    "https://upload.wikimedia.org/wikipedia/commons/6/6d/Dinh_%C4%90%E1%BB%99c_l%E1%BA%ADp.JPG"
            ));
            return result;
        } else if (normalizedQuery.contains("lang bac") || normalizedQuery.contains("lang ho chi minh")) {
            result.put("text", "Lăng Bác là nơi hội tụ và lan tỏa các giá trị truyền thống văn hóa, lịch sử của dân tộc việt nam\n\n" +
                    "Thể theo ý nguyện thiết tha của toàn Đảng, toàn dân, trong phiên họp sáng 29/11/1969, Bộ Chính trị Trung ương Đảng đã bàn và quyết định: Với tấm lòng kính yêu vô hạn và đời đời nhớ ơn Chủ tịch Hồ Chí Minh, chúng ta phải thực hiện đến mức tốt nhất nhiệm vụ giữ gìn lâu dài thi hài Chủ tịch Hồ Chí Minh và xây dựng Lăng của Người.\n\n" +
                    "Đảng và Nhà nước ta quyết định xây dựng lăng của Người tại Quảng trường Ba Đình lịch sử, nơi Người đọc bản Tuyên ngôn độc lập, tuyên bố thành lập nước Việt Nam Dân chủ Cộng hòa.\n\n" +
                    "Lăng Bác là một công trình kiến trúc đồ sộ, uy nghi; lăng cao 21,6 mét, bề mặt rộng 31 mét. Hai cánh gà mở ra hai phía.\n" +
                    "Phần dưới Lăng lát đá hoa cương mầu sẫm gồm ba tầng, tầng trên nhỏ hơn tầng dưới, hình thành một tam cấp đồ sộ. Nét độc đáo của kiến trúc dân tộc đã tạo cho Lăng một thế đứng vững chãi, trang nghiêm.\n\n" +
                    "Phần mái Lăng cũng hình thành một tam cấp nhẹ nhõm, thanh thoát với những đường vắt chéo, làm cho mái Lăng vừa mang những nét gọn gàng, giản dị của kiến trúc hiện đại, vừa phảng phất dáng vẻ mềm mại, uyển chuyển của mái cong kiến trúc dân tộc cổ truyền.\n" +
                    "Dưới mái Lăng, bốn phía đều có các hàng cột cao, to bằng đá hoa cương màu xám bạc.\n\n" +
                    "Sáng 29/8/1975, Đảng và Nhà nước đã tổ chức lễ trọng thể khánh thành Lăng Chủ tịch Hồ Chí Minh và đưa Người về an nghỉ mãi mãi ở nơi đây, giữa trái tim của toàn dân tộc\n\n" +
                    "Bên trong bốn hàng cột trang nghiêm là bốn bức tường đá hoa cương đỏ màu son: đó là căn phòng yên nghỉ vĩnh cửu của Chủ tịch Hồ Chí Minh.\n" +
                    "Sau 700 ngày đêm lao động của cán bộ, chiến sỹ, công nhân viên xây dựng Lăng, và đặc biệt là có sự giúp đỡ bằng sức người và sức của của Đảng, Chính phủ và nhân dân Liên Xô, chúng ta đã vượt qua trăm nghìn gian khó xây dựng nên ngôi nhà vĩnh hằng của Bác.\n\n" +
                    "Sáng 29/8/1975, Đảng và Nhà nước đã tổ chức lễ trọng thể khánh thành Lăng Chủ tịch Hồ Chí Minh và đưa Người về an nghỉ mãi mãi ở nơi đây, giữa trái tim của toàn dân tộc. Việc xây dựng Lăng của Người có sự giúp đỡ nhiệt tình của Chính phủ Liên Xô. Từ ngày 9-23/1/1970, Chính phủ Liên Xô đã cử một đoàn gồm 7 cán bộ sang Việt Nam để bàn về việc thiết kế Lăng Chủ tịch Hồ Chí Minh. Chỉ trong một tuần, các chuyên gia Liên Xô và Việt Nam đã soạn thảo xong bản “Dự thảo nhiệm vụ thiết kế Lăng Chủ tịch Hồ Chí Minh.”\n\n" +
                    "Ngày 19/10/1970, bản dự thảo đã được thông qua tại phiên họp Bộ Chính trị. Trong hơn một tháng, tập thể kiến trúc sư, kỹ sư và cán bộ kỹ thuật của Việt Nam đã hoàn thành phương án “thiết kế sơ bộ” của Lăng.\n\n" +
                    "Thủ tướng Phạm Văn Đồng đã ký quyết định lấy ngày 2/9/1973 là ngày khởi công và ngày 2/9/1975 là ngày hoàn thành, đưa công trình vào hoạt động.\n" +
                    "Từ ngày 19/3 đến ngày 6/5/1970, một đoàn cán bộ gồm ba kiến trúc sư Việt Nam đã mang bản “thiết kế sơ bộ” sang tiếp tục làm việc với bạn. Dựa trên những phương án đã có của hai đoàn, một phương án chung có tăng cường các giải pháp kỹ thuật phù hợp với môi trường khí hậu nhiệt đới của Việt Nam đã được hình thành. Bản thiết kế này được đặt phiên hiệu là công trình 75808.\n\n" +
                    "Cũng trong thời gian này, rất nhiều thư từ mọi miền Tổ quốc và của cả Việt kiều ở nước ngoài gửi về bày tỏ nguyện vọng được đóng góp, kiến nghị và thiết kế Lăng. Thể theo nguyện vọng của nhân dân, Bộ Chính trị Trung ương Đảng quyết định lùi việc duyệt bản “thiết kế sơ bộ” lại 4 đến 5 tháng để tổ chức một đợt sáng tác các mẫu thiết kế Lăng và trưng bày các mẫu sáng tác đó, lấy ý kiến tham gia của nhân dân.\n\n" +
                    "Sau khi đợt sáng tác mẫu được phát động, từ cuối tháng 5/1970 đến cuối tháng 8/1970, Ban tổ chức đã nhận được hơn 200 phương án thiết kế khác nhau của 16 đơn vị, ngành và nhiều cá nhân gửi tới. Ban tổ chức đã chọn ra được 24 phương án có nhiều ưu điểm và tổ chức trưng bày tại 5 địa điểm: Hà Nội, Hải Phòng, Thái Nguyên, Sơn La và Nghệ An. Tổng cộng có 745.487 lượt người tới thăm và 34.022 người tham gia ý kiến.\n" +
                    "Sau 10 ngày kết thúc đợt triển lãm mô hình Lăng, bản “thiết kế sơ bộ” tổng hợp ý kiến nhân dân đã được đoàn cán bộ mang sang Liên Xô làm việc với các chuyên gia.\n\n" +
                    "Ngày 9/2/1971, tại Moskva, “Hiệp nghị giữa Chính phủ Việt Nam Dân chủ Cộng hòa và Chính phủ Cộng hòa xã hội chủ nghĩa XôViết về việc Liên Xô giúp đỡ kỹ thuật cho Việt Nam trong việc giữ gìn thi hài của Chủ tịch Hồ Chí Minh và xây dựng Lăng của Người được đại diện của hai Chính phủ là Phó Thủ tướng Lê Thanh Nghị và Phó Chủ tịch Hội đồng Bộ trưởng Liên Xô Nôvicốp ký kết.\n\n" +
                    "Ngày 3/11/1971, Thủ tướng Phạm Văn Đồng ký quyết định chính thức thành lập Ban phụ trách xây dựng Lăng Chủ tịch Hồ Chí Minh. Cùng ngày, Phó Thủ tướng Đỗ Mười đã ký quyết định thành lập Ban chỉ huy công trình xây dựng Lăng Chủ tịch Hồ Chí Minh.\n" +
                    "Ngày 31/12/1971, Thường vụ Hội đồng Chính phủ đã ký quyết định phê chuẩn bản “thiết kế kỹ thuật.”\n\n" +
                    "Ngày 5/2/1972, Thủ tướng Chính phủ ra quyết định chính thức phân công nhiệm vụ cho các bộ, các ngành, các địa phương tham gia xây dựng công trình 75808, trong đó hai lực lượng nòng cốt là Bộ Kiến trúc và Bộ Quốc phòng.\n" +
                    "Lăng Chủ tịch Hồ Chí Minh là một công trình văn hóa, nghệ thuật, phần công việc trang trí và hoàn thiện chiếm hơn một nửa thời gian xây dựng. Phần công tác này đòi hỏi trình độ kỹ thuật và mỹ thuật rất cao. Nhìn từ ngoài Lăng, cũng như đi sâu vào bên trong, người xem dễ nhận thấy toàn bộ khối Lăng chủ yếu được kết cấu, trang trí bằng đá.\n\n" +
                    "Đảng, Nhà nước và nhân dân Liên Xô đã gửi tặng Việt Nam hai vạn miếng đá hoa cương và cẩm thạch mài nhẵn. Ngày 1/11/1974, viên đá đầu tiên được ốp vào công trình Lăng. Sau khi viên đá đầu tiên được ốp ở phòng khách, hàng loạt bức tường khác đã được ốp đá, mỗi phòng, mỗi tường có những quy cách khác nhau tạo dáng phong phú đa dạng, phù hợp với ánh sáng, mầu sắc, hài hòa với bố cục chung. Mặt ngoài của Lăng được ốp bằng đá hoa cương mầu xám đậm, tạo vẻ tôn nghiêm thành kính. Chữ “Chủ tịch Hồ Chí Minh” trên nóc lăng được ghép bằng đá ngọc Cao Bằng. Cửa chính của Lăng được ốp bằng đá đen bóng.\n\n" +
                    "Hai phòng khách và lối ra lễ đài, các nền và bậc cầu thang cũng lát bằng đá hoa cương. Tất cả các tường và cột ốp bằng đá cẩm thạch. Riêng tường chính tiền sảnh ốp đá hoa cương vân đỏ hồng tươi, làm nền cho dòng chữ “Không có gì quý hơn độc lập, tự do” và chữ ký của Bác được mạ vàng rực rỡ. Phòng Bác nằm, ốp bằng đá cẩm thạch Hà Tây, những viên đá có hình chữ nhật xếp thẳng đứng kế tiếp nhau nối từ chân tường đến đỉnh trần làm ta liên tưởng tới những thanh gỗ lát nhà sàn của Bác.\n\n" +
                    "Hai lá cờ: cờ Đảng và cờ Tổ quốc được ghép bằng 4.000 miếng đá hồng ngọc của Thanh Hóa, Búa Liềm và sao năm cánh ghép bằng đá cẩm vân vàng sáng. 200 bộ cửa được các nghệ nhân mộc Nam Hà, Hà Bắc, Nghệ An đóng với kỹ xảo điêu luyện.\n\n" +
                    "Từ mọi miền đất nước, nhân dân đóng góp những vật liệu đặc sản của địa phương mình cho công trình: Ximăng của Nhà máy Ximăng Hải Phòng; đá dăm ở khu vực Thác Bà, Xuân Hòa; Cát vàng Kim Bôi, Hòa Bình; gỗ của miền Đông Nam Bộ, Tây Nguyên…\n\n" +
                    "Lăng Chủ tịch Hồ Chí Minh là một công trình có nhiều hệ thống máy móc hiện đại nhằm giữ gìn nguyên vẹn lâu dài thi hài Bác.\n\n" +
                    "Từ tháng 9/1973, một đoàn cán bộ kỹ thuật điện, cấp thoát nước, thông hơi, điều hòa, cơ khí sang Liên Xô tham gia thiết kế thi công phần lắp và nắm trước thiết kế, nắm trước các biện pháp thi công. Tháng 3/1974, bản thiết kế thi công điện, nước hoàn thành, và tới tháng 4, phần thiết kế thi công thông hơi, điều hòa kết thúc. Cuối tháng 12/1974, cán bộ, chiến sỹ, công nhân viên công trường đã cơ bản hoàn thành lắp hệ mạng của hệ kỹ thuật.\n\n" +
                    "Hệ trung tâm điều hòa không khí được coi như lá phổi của công trình, do Liên Xô thiết kế và đặt hàng cho một số nước khác sản xuất. Có tất cả 17 hệ thông hơi, điều hòa, 4 hệ điều hòa trung tâm nặng 160 tấn rất hiện đại. Hỗ trợ cho hệ điều hòa trung tâm còn có các bộ làm lạnh cục bộ, các bộ sấy cục bộ, các máy điều hoà treo, ngoài ra còn có 620 thiết bị lẻ như tiêu âm, van gió, môtơ, lưới hút, thổi… Và một nhà máy lạnh có sáu cụm máy lạnh với tổng công suất hơn 2,5 triệu kilô calo/giờ. Lăng có 3 hệ thống cấp và thoát nước với 5 bình chứa nước dung tích từ 10 đến 50m3, gần 50 máy bơm các loại, hơn 450 van khóa và 5.000mét ống nước.\n\n" +
                    "Đặc biệt, các máy móc ở đây được thiết kế khá độc đáo, yêu cầu lắp ráp với độ chính xác cao. Trong các loại máy móc thiết bị tinh vi quan trọng có thiết bị quan tài. Thiết bị này do các chuyên gia lắp. Quan tài trong suốt và kín. Máy móc nâng hạ quan tài cũng theo nguyên lý chuyển động chính xác đặc biệt. 20 loại đèn nhiều tia, có màu khúc xạ bởi nhiều bộ lăng kính và hệ thoát nhiệt. Trình độ công nghệ và trình độ khoa học ở thiết bị này rất cao. \n" +
                    "Cùng với việc thiết kế, xây dựng Lăng Bác là việc thiết kế, cải tạo xây dựng lại Quảng trường Ba Đình. Quảng trường Ba Đình, vườn hoa tiếp giáp và Lăng Bác là một quần thể kiến trúc thống nhất. Tổng diện tích cải tạo và xây dựng là 14ha. Quảng trường ở phía trước Lăng có diện tích 20.000m2, chia thành 176 ô vuông trồng cỏ (từ ngày 14/3 đến 17/7/2000 vừa qua đã tôn tạo lại thảm cỏ với hệ thống tưới phun tự động), giữa có lối đi rộng 1,4 mét. Xung quanh Quảng trường là hè rộng 7 mét và 4 mét lát bằng tấm bêtông cốt thép sỏi nổi trang trí. Tổng diện tích lát hè 7.800m2. Dưới mặt đất là hệ thống tiêu thoát nước. Nước được thu dần về hai trạm bơm đặt ngầm dưới mặt đất.\n\n" +
                    "Đường Hùng Vương, đi qua trước Lăng làm bằng bêtông cốt thép, dài 1.060 mét, riêng đoạn trước Lăng rộng 60 mét. Đường Bắc Sơn dài 280 mét, rộng 60 mét, chia làm hai làn, ở giữa là dải phân cách rộng 12 mét làm vườn hoa. Đường Ba Đình dài 400 mét, rộng 18 mét. Ngoài ra còn có đường xung quanh Lăng gồm các đoạn ra vào vườn hoa hai bên và phía sau Lăng…\n\n" +
                    "Để Quảng trường được khô ráo nhưng vẫn bảo đảm cho hàng trăm thứ cây cảnh có thể sống tốt tươi, một hệ thống ống cống bằng bê tông cốt thép đã được đặt ngầm dưới các hè dọc đường với tổng chiều dài 4.200 mét. Dưới các ô vuông cỏ của Quảng trường có các tầng lọc nước, mạng ống và mương ngầm. Hệ thống cấp nước được bố trí trên các khu vực Quảng trường sau Lăng và đường Bắc Sơn.\n\n" +
                    "Quảng trường sử dụng các đèn thủy ngân cao áp đặt trên các cột cao. Quảng trường còn có một hệ thống thông tin, truyền thanh, truyền hình. Các công trình này sẽ đảm bảo thông tin liên lạc, truyền thanh, thu thanh và thu phát hình tại chỗ.\n\n" +
                    "Công trình cây xanh, cây cảnh và vườn hoa làm tôn vẻ đẹp và tạo ra không khí trong lành cho toàn bộ khu vực Lăng và Quảng trường Ba Đình. Với tấm lòng kính yêu Bác vô hạn, các địa phương trên mọi miền đất nước đã gửi về Thủ đô những cây xanh, những loại hoa tiêu biểu cho vùng đất của mình.");
            result.put("images", Arrays.asList(
                    "https://upload.wikimedia.org/wikipedia/commons/5/5e/Lascar_Ho_Ch%C3%AD_Minh_Mausoleum_%284550987354%29.jpg",
                    "https://upload.wikimedia.org/wikipedia/commons/3/3f/Ho_Chi_Minh_tomb.jpg"
            ));
            return result;
        } else if (normalizedQuery.contains("hoang thanh") || normalizedQuery.contains("thang long")) {
            result.put("text", "Hoàng thành Thăng Long: Di Sản Giữa Lòng Hà Nội\n\n" +
                    "Ý nghĩa của công trình Hoàng thành Thăng Long\n\n" +
                    "Hoàng thành Thăng Long là minh chứng sống động cho tiến trình lịch sử kéo dài hơn 13 thế kỷ của Đại Việt. Với vai trò là trung tâm quyền lực chính trị qua nhiều triều đại, nơi đây ghi dấu những quyết sách quan trọng định hình vận mệnh đất nước. Những di tích còn sót lại, từ cổng thành, điện Kính Thiên cho đến các dấu tích khảo cổ, đều mang giá trị lịch sử và văn hóa to lớn, phản ánh sự phát triển của nghệ thuật kiến trúc và tư duy của người Việt cổ.\n\n" +
                    "Không những vậy, Hoàng thành còn là biểu tượng cho tinh thần dựng nước, giữ nước, sự kiên cường của dân tộc qua bao biến cố thăng trầm. Được UNESCO công nhận là Di sản Văn hóa Thế giới, Hoàng thành Thăng Long ngày nay không chỉ là một địa điểm du lịch nổi tiếng mà còn là niềm tự hào của người Việt Nam, góp phần quảng bá hình ảnh văn hóa Việt Nam ra thế giới.\n\n" +
                    "Các địa điểm tham quan đặc sắc trong khuôn viên Hoàng thành Thăng Long:\n\n" +
                    "1. Đoan Môn (Cửa Nam)\n\n" +
                    "Đoan Môn hay Cửa Nam là cổng chính dẫn vào khu trung tâm của Hoàng thành Thăng Long, từng là lối đi dành riêng cho vua và các quan đại thần. Cổng được xây dựng kiên cố bằng gạch đá xếp chồng với năm lối đi hình vòm, trong đó cửa trung tâm chỉ dành cho hoàng đế.\n\n" +
                    "Phía trên Đoan Môn có một tầng lầu từng được sử dụng để quan sát và kiểm soát lối ra vào Hoàng thành. Những họa tiết chạm khắc trên cổng mang dấu ấn giao thoa giữa kiến trúc Việt Nam và Trung Hoa, thể hiện sự tinh xảo trong nghệ thuật xây dựng cung đình thời phong kiến. Đây là một trong những công trình nguyên vẹn nhất của Hoàng thành, giúp du khách hình dung rõ hơn về sự bề thế của kinh thành Thăng Long xưa.\n\n" +
                    "1. Điện Kính Thiên\n\n" +
                    "Là trung tâm quyền lực của Hoàng thành Thăng Long, Điện Kính Thiên từng là nơi diễn ra các nghi lễ quan trọng và các hoạt động triều chính dưới thời Lê và Nguyễn. Dù phần lớn công trình đã bị phá hủy trong thời kỳ thuộc địa, nền móng và bậc thềm rồng đá vẫn còn tồn tại, minh chứng cho sự uy nghi của cung điện hoàng gia một thời.\n" +
                    "Nổi bật nhất là bậc thềm rồng dẫn lên điện với những đường nét chạm khắc tinh xảo, thể hiện đỉnh cao nghệ thuật điêu khắc thời Lê Sơ. Các nhà sử học tin rằng Điện Kính Thiên từng là nơi đặt ngai vàng của hoàng đế. Ngày nay, khu vực này vẫn là địa điểm nghiên cứu quan trọng, đồng thời là nơi tổ chức các sự kiện văn hóa nhằm tái hiện phần nào diện mạo cung điện xưa.\n\n" +
                    "1. Hậu Lâu (Lầu Công Chúa)\n\n" +
                    "Hậu Lâu hay còn gọi là Lầu Công Chúa, được cho là nơi ở của các cung phi và công chúa trong hoàng tộc. Tòa nhà mang phong cách kiến trúc cổ điển Việt Nam với mái ngói cong và tường dày giúp điều hòa không khí, tạo không gian mát mẻ vào mùa hè và ấm áp vào mùa đông.\n\n" +
                    "So với các công trình khác trong Hoàng thành, Hậu Lâu mang vẻ đẹp thanh tao, trầm mặc, gợi lên hình ảnh cuộc sống cung đình xưa. Hiện nay, nơi đây trưng bày nhiều tư liệu và hiện vật liên quan đến đời sống hoàng gia, giúp du khách hiểu thêm về vị trí và vai trò của nữ giới trong hoàng tộc phong kiến Việt Nam.\n\n" +
                    "1. Nhà và Hầm D67\n\n" +
                    "Nhà D67 là công trình quan trọng trong giai đoạn kháng chiến chống Mỹ, từng là nơi làm việc của Bộ Tổng Tham mưu và Quân ủy Trung ương Quân đội Nhân dân Việt Nam. Tại đây, nhiều quyết định chiến lược đã được đưa ra, bao gồm kế hoạch cho cuộc Tổng tiến công và nổi dậy Mậu Thân 1968.\n\n" +
                    "Công trình có thiết kế đặc biệt với tường bê tông dày và trần nhà gia cố để chống bom, đảm bảo an toàn tối đa cho các cuộc họp quân sự quan trọng. Bên trong Nhà D67, du khách có thể thấy các bản đồ tác chiến, điện thoại liên lạc, bàn ghế làm việc vẫn được giữ nguyên, tái hiện không gian chỉ huy trong thời chiến. Đây là một điểm tham quan quan trọng giúp người xem hiểu rõ hơn về chiến lược quân sự và tinh thần đấu tranh của dân tộc trong thời kỳ kháng chiến.\n\n" +
                    "1. Chính Bắc Môn (Cửa Bắc)\n\n" +
                    "Chính Bắc Môn hay Cửa Bắc là cổng thành duy nhất còn lại của Hoàng thành Thăng Long, mang trên mình những dấu tích chiến tranh từ thế kỷ 19. Công trình được xây dựng bằng gạch và đá, với thiết kế kiên cố nhằm bảo vệ kinh thành khỏi các cuộc tấn công từ phía Bắc.\n\n" +
                    "Những vết đạn đại bác còn in trên tường thành là minh chứng cho cuộc kháng chiến chống thực dân Pháp đầy kiên cường của nhân dân ta. Bên trong cổng có một phòng trưng bày nhỏ, lưu giữ các hiện vật và tư liệu lịch sử liên quan đến quá trình bảo vệ kinh thành. Du khách cũng có thể leo lên đỉnh cổng để ngắm toàn cảnh khu Hoàng thành từ trên cao.\n\n" +
                    "1. Cột cờ Hà Nội\n\n" +
                    "Cột cờ Hà Nội là một trong những biểu tượng lịch sử tiêu biểu của thủ đô, được xây dựng vào năm 1812 dưới triều Nguyễn với mục đích quan sát quân sự. Công trình cao 33,4 mét, bao gồm ba tầng đế hình vuông và một tháp lục giác phía trên. Đây là một trong số ít kiến trúc của Hoàng thành Thăng Long không bị phá hủy trong thời kỳ Pháp thuộc, giữ nguyên giá trị lịch sử qua nhiều biến cố.\n\n" +
                    "Bên trong tháp có cầu thang xoắn dẫn lên các ô cửa sổ quan sát, từng được sử dụng như trạm canh gác quan trọng của kinh thành xưa. Khi đêm xuống, Cột cờ Hà Nội trở nên lung linh dưới ánh đèn, nổi bật giữa bầu trời thành phố, tạo nên khung cảnh đầy ấn tượng.\n\n" +
                    "1. Khu khảo cổ số 18 Hoàng Diệu\n\n" +
                    "Nằm ngay trong khuôn viên Hoàng thành, khu khảo cổ 18 Hoàng Diệu là nơi phát hiện nhiều dấu tích quan trọng của kinh thành xưa. Khu vực này bao gồm hàng loạt hố khai quật với nền móng cung điện, giếng cổ, hệ thống thoát nước bằng gạch thời Lý - Trần, phản ánh sự phát triển liên tục của Hoàng thành qua các thời kỳ. Tại đây, du khách có thể chiêm ngưỡng hàng nghìn di vật cổ như gạch lát nền thời Lý, ngói mũi sen, gốm sứ men ngọc, cùng nhiều vật phẩm trang trí cung điện của các triều đại phong kiến.");
            result.put("images", Arrays.asList(
                    "https://res.cloudinary.com/dlmo3dq0p/image/upload/v1763565045/ho%C3%A0ng_th%C3%A0nh_th%C4%83ng_long_-_post_1_lujhju.png",
                    "https://upload.wikimedia.org/wikipedia/commons/2/2c/Hanoi_citadel.jpg"
            ));
            return result;
        }
        return result; // Empty
    }
}